stages:
  extract:
    cmd: python image_similarity_search/pre_processing.py -i data/raw/catalogue -o data/interim/dataset.csv -m data/interim/mapping.csv
    deps:
    - data/interim/mapping.csv
    - data/raw/catalogue
    - image_similarity_search/pre_processing.py
    outs:
    - data/interim/dataset.csv

  split:
    cmd: python image_similarity_search/split.py -i data/interim/dataset.csv --train-path data/processed/train.csv --test-path  data/processed/test.csv
    deps:
    - data/interim/dataset.csv
    - image_similarity_search/split.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train_autoencoder:
    cmd: python image_similarity_search/autoencoder.py --train_path "data/processed/train.csv" --test_path "data/processed/test.csv" --save_path "models/autoencoder.pth"
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - image_similarity_search/autoencoder.py
    outs:
    - models/autoencoder.pth

  evaluate_autoencoder:
    cmd: python image_similarity_search/evaluation.py --test_path "data/processed/test.csv" --weights_path "models/autoencoder.pth"
    deps:
    - data/processed/test.csv
    - models/autoencoder.pth