name: image_similarity_search
channels:
  - pytorch
  - conda-forge
  - anaconda
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12.7
  - pytorch=2.5.1
  - pyyaml=6.0.2
  - pyyaml-env-tag=0.1
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=75.1.0
  - six=1.16.0
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - wheel=0.44.0
  - yaml=0.2.5
  - ipykernel=6.29.5
  - ipython=8.28.0
  - isort=5.13.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - numpy=1.26.4
  - pip=24.2
  - pandas=2.2.2
  - pytest=7.4.4
  - pip:
      - openpyxl==3.1.5
      - tqdm==4.67.1
      - transformers==4.46.3
      - dagshub==0.3.40
      - dvc==3.56.0
      - dvc-s3==3.2.0
      - mlflow==2.17.1
      - mlflow-skinny==2.17.1
      - umap-learn==0.5.7
      - py-cpuinfo==9.0.0
      - git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1#egg=clip
      - fastapi==0.103.1
      - fastapi-cli==0.0.5
      - python-multipart==0.0.19
      - uvicorn==0.32.1
      - astroid==3.3.6
      - pylint==3.3.2
      - ruff==0.8.3
      - qdrant-client==1.12.1
      - codecarbon==2.8.1